name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64 -t bunnypranav/bunnysbot:arm64 .
    - name: Push the Docker image
      run: docker login -u bunnypranav -p ${{ secrets.DOCKER_TOKEN }} && docker push bunnypranav/bunnysbot:arm64
